### ISSUE TITLE
crash on opening serial port

### ISSUE THREAD

**Issue by jegb** [cody82/grblgui#8]
java.lang.NumberFormatException: For input string: "rm"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at cody.grbl.GrblStream$Reader.run(GrblStream.java:216)
	at java.lang.Thread.run(Thread.java:745)
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by cody82** [comment]
Which Grbl version do you use?

**Comment by jegb** [comment]
0.9j
